spring:
  config:
    activate:
      on-profile: home
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kjc?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 12345
#  data:
#    mongodb:
#      host: 192.168.35.222
#      port: 27017
#      authentication-database: csms_log
#      database: LogTest
#      username: everon_dev
#      password: Everon!01
